# Site settings
title: Ali Ok - Blog & Project showcase
email: aliok (AT) apache (DOT) org
description: > # this means to ignore newlines until "baseurl:"
  Ali Ok's blog and project showcase. All content is under Apache License 2.0.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aliok.github.io" # the base hostname & protocol for your site
twitter_username: aliok_tr
github_username:  aliok

# Build settings
markdown: kramdown
highlighter: pygments
